name: push-deploy-world

on:
  push:
  pull_request:

jobs:
  push-or-pr:
    uses: ./.github/workflows/deploy-to-github-pages.yml
    permissions:
      contents: read
      pages: write
      id-token: write
